use Scancode;
use Scancode::*;

/// Keyboard scancode map for Microsoft Windows.
pub static MAP: [Option<Scancode>; 94] = [None,
                                          Some(Escape),
                                          Some(Num1),
                                          Some(Num2),
                                          Some(Num3),
                                          Some(Num4),
                                          Some(Num5),
                                          Some(Num6),
                                          Some(Num7),
                                          Some(Num8),
                                          Some(Num9),
                                          Some(Num0),
                                          Some(Minus),
                                          Some(Equals),
                                          Some(Backspace),
                                          Some(Tab),
                                          Some(Q),
                                          Some(W),
                                          Some(E),
                                          Some(R),
                                          Some(T),
                                          Some(Y),
                                          Some(U),
                                          Some(I),
                                          Some(O),
                                          Some(P),
                                          Some(LeftBracket),
                                          Some(RightBracket),
                                          Some(Enter),
                                          Some(LeftControl),
                                          Some(A),
                                          Some(S),
                                          Some(D),
                                          Some(F),
                                          Some(G),
                                          Some(H),
                                          Some(J),
                                          Some(K),
                                          Some(L),
                                          Some(Semicolon),
                                          Some(Apostrophe),
                                          Some(Grave),
                                          Some(LeftShift),
                                          Some(Backslash),
                                          Some(Z),
                                          Some(X),
                                          Some(C),
                                          Some(V),
                                          Some(B),
                                          Some(N),
                                          Some(M),
                                          Some(Comma),
                                          Some(Period),
                                          Some(Slash),
                                          Some(RightShift),
                                          Some(PadMultiply), // Also PrintScreen
                                          Some(LeftAlt),
                                          Some(Space),
                                          Some(CapsLock),
                                          Some(F1),
                                          Some(F2),
                                          Some(F3),
                                          Some(F4),
                                          Some(F5),
                                          Some(F6),
                                          Some(F7),
                                          Some(F8),
                                          Some(F9),
                                          Some(F10),
                                          Some(NumLock),
                                          Some(ScrollLock),
                                          Some(Home), // Also Pad7
                                          Some(Up), // Also Pad8
                                          Some(PageUp), // Also Pad9
                                          Some(PadMinus),
                                          Some(Left), // Also Pad4
                                          Some(Pad5),
                                          Some(Right), // Also Pad6
                                          Some(PadPlus),
                                          Some(End), // Also Pad1
                                          Some(Down), // Also Pad2
                                          Some(PageDown), // Also Pad3
                                          Some(Insert), // Also Pad0
                                          Some(Delete), // Also PadDecimal
                                          None,
                                          None,
                                          Some(NonUsBackslash),
                                          Some(F11),
                                          Some(F12),
                                          Some(Pause),
                                          None,
                                          Some(LeftGui),
                                          Some(RightGui),
                                          Some(Menu)];
